from fastapi import APIRouter, Body, Depends, Request
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.core.security import get_current_user_allow_pending, get_user_roles
from app.core.audit import write_audit_log
from app.core.rate_limit import limiter
from app.models.user import User
from app.models.branch import Branch
from app.models.supplier import Supplier
from app.schemas.auth import (
    LoginRequest,
    TokenResponse,
    RefreshRequest,
    LogoutRequest,
    ChangePasswordRequest,
    ChangePasswordResponse,
    RedeemRecoveryTokenRequest,
    CurrentUserResponse,
)
from app.services import auth_service

router = APIRouter(prefix="/auth")


@router.post("/login", response_model=TokenResponse)
@limiter.limit("10/minute")
def login(payload: LoginRequest, request: Request, db: Session = Depends(get_db)):
    access_token, refresh_token, role, redirect_to, must_change = auth_service.authenticate(
        db, payload.username, payload.password, ip_address=request.client.host if request.client else None
    )
    return TokenResponse(
        access_token=access_token,
        refresh_token=refresh_token,
        role=role,
        redirect_to=redirect_to,
        must_change_password=must_change,
    )


@router.post("/refresh", response_model=TokenResponse)
def refresh(payload: RefreshRequest, db: Session = Depends(get_db)):
    access_token, refresh_token, role, redirect_to, must_change = auth_service.refresh_session(db, payload.refresh_token)
    return TokenResponse(
        access_token=access_token,
        refresh_token=refresh_token,
        role=role,
        redirect_to=redirect_to,
        must_change_password=must_change,
    )


@router.post("/logout")
def logout(
    payload: LogoutRequest | None = Body(default=None),
    current_user: User = Depends(get_current_user_allow_pending),
    db: Session = Depends(get_db),
):
    """
    Ends this session: the refresh token the client sends is revoked, so it cannot mint new access
    tokens. (The short-lived access token simply runs out.) Other sessions on the same shared
    branch/supplier login are untouched. Older clients that send no body still log out locally.
    """
    revoked = auth_service.revoke_refresh_token(db, current_user, payload.refresh_token if payload else None)
    write_audit_log(
        db,
        user_id=current_user.id,
        role=None,
        action="LOGOUT",
        entity_type="user",
        entity_id=current_user.id,
        description=None if revoked else "No refresh token supplied/valid - session not server-revoked.",
    )
    return {"detail": "Logged out."}


@router.post("/redeem-recovery-token")
@limiter.limit("10/minute")
def redeem_recovery_token(payload: RedeemRecoveryTokenRequest, request: Request, db: Session = Depends(get_db)):
    """
    Sets a new password using a one-time recovery token generated by
    scripts/generate_recovery_token.py — the break-glass path for an
    account (typically Admin) that's otherwise completely locked out.
    Deliberately public/unauthenticated: someone who can't log in at all
    has nothing else to authenticate this request with. Rate-limited the
    same as /login since it's the same class of endpoint — an
    unauthenticated request that takes a secret and a password.
    """
    auth_service.redeem_recovery_token(db, payload.token, payload.new_password)
    return {"detail": "Password reset. You can now log in with your new password."}


@router.post("/change-password", response_model=ChangePasswordResponse)
def change_password(
    payload: ChangePasswordRequest,
    current_user: User = Depends(get_current_user_allow_pending),
    db: Session = Depends(get_db),
):
    access_token, refresh_token = auth_service.change_password(
        db, current_user, payload.current_password, payload.new_password
    )
    return ChangePasswordResponse(access_token=access_token, refresh_token=refresh_token)


@router.get("/me", response_model=CurrentUserResponse)
def me(current_user: User = Depends(get_current_user_allow_pending), db: Session = Depends(get_db)):
    roles = get_user_roles(db, current_user.id)
    role = roles[0] if roles else ""
    branch_name = None
    supplier_name = None
    if current_user.branch_id:
        branch = db.get(Branch, current_user.branch_id)
        branch_name = branch.branch_name if branch else None
    if current_user.supplier_id:
        supplier = db.get(Supplier, current_user.supplier_id)
        supplier_name = supplier.supplier_name if supplier else None
    return CurrentUserResponse(
        id=current_user.id,
        username=current_user.username,
        role=role,
        must_change_password=current_user.must_change_password,
        branch_id=current_user.branch_id,
        branch_name=branch_name,
        supplier_id=current_user.supplier_id,
        supplier_name=supplier_name,
    )
