import { FormEvent, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { apiFetch, ApiError } from "../../api/client";

// Break-glass account recovery: redeems a one-time token generated by
// scripts/generate_recovery_token.py (run by whoever has direct server
// access) to set a new password without needing to already be logged in.
// This is the only recovery path in the app — there's no self-service
// "forgot password" and no email-based reset (no SMTP configured).
export default function RecoverAccountPage() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const [token, setToken] = useState(searchParams.get("token") ?? "");
  const [newPassword, setNewPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState(false);

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    setError(null);
    if (newPassword.length < 8) {
      setError("New password must be at least 8 characters.");
      return;
    }
    if (newPassword !== confirmPassword) {
      setError("Passwords don't match.");
      return;
    }
    setSubmitting(true);
    try {
      await apiFetch("/auth/redeem-recovery-token", {
        method: "POST",
        body: JSON.stringify({ token: token.trim(), new_password: newPassword }),
      });
      setSuccess(true);
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Could not reach the server. Please try again.");
    } finally {
      setSubmitting(false);
    }
  }

  if (success) {
    return (
      <div className="min-h-screen flex items-center justify-center px-4 bg-gray-50 font-body">
        <div className="bg-white rounded-[2rem] shadow-[0_30px_60px_-15px_rgba(21,56,38,0.25)] p-8 max-w-md w-full text-center motion-safe:animate-fade-up">
          <p className="text-crate-700 font-semibold text-lg">Password reset.</p>
          <p className="text-crate-800/60 text-sm mt-2">You can now sign in with your new password.</p>
          <button
            onClick={() => navigate("/login", { replace: true })}
            className="mt-6 bg-gradient-to-b from-crate-700 to-crate-800 text-white rounded-full px-6 py-2.5 text-sm font-semibold hover:brightness-110 active:scale-[0.98] transition-all duration-200"
          >
            Go to sign in
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex items-center justify-center px-4 bg-gray-50 font-body">
      <form
        onSubmit={handleSubmit}
        className="bg-white rounded-[2rem] shadow-[0_30px_60px_-15px_rgba(21,56,38,0.25)] p-8 max-w-md w-full motion-safe:animate-fade-up"
      >
        <h1 className="font-display font-bold text-xl text-crate-950">Recover account access</h1>
        <p className="text-sm text-crate-800/60 mt-1.5 mb-6">
          Use the one-time recovery token your administrator or server operator gave you. It's valid for 30
          minutes and works once.
        </p>

        <label htmlFor="token" className="block text-xs font-semibold uppercase tracking-wide text-crate-800/70 mb-1.5">
          Recovery Token
        </label>
        <input
          id="token"
          value={token}
          onChange={(e) => setToken(e.target.value)}
          required
          autoFocus={!token}
          className="w-full border border-sage-300 bg-sage-50/60 rounded-full px-4 py-2.5 text-sm mb-4 focus:outline-none focus:ring-2 focus:ring-crate-700/30 focus:border-crate-700 focus:bg-white transition-all duration-150"
        />

        <label htmlFor="newPassword" className="block text-xs font-semibold uppercase tracking-wide text-crate-800/70 mb-1.5">
          New Password
        </label>
        <input
          id="newPassword"
          type="password"
          value={newPassword}
          onChange={(e) => setNewPassword(e.target.value)}
          required
          minLength={8}
          placeholder="At least 8 characters"
          className="w-full border border-sage-300 bg-sage-50/60 rounded-full px-4 py-2.5 text-sm mb-4 focus:outline-none focus:ring-2 focus:ring-crate-700/30 focus:border-crate-700 focus:bg-white transition-all duration-150"
        />

        <label htmlFor="confirmPassword" className="block text-xs font-semibold uppercase tracking-wide text-crate-800/70 mb-1.5">
          Confirm New Password
        </label>
        <input
          id="confirmPassword"
          type="password"
          value={confirmPassword}
          onChange={(e) => setConfirmPassword(e.target.value)}
          required
          minLength={8}
          className="w-full border border-sage-300 bg-sage-50/60 rounded-full px-4 py-2.5 text-sm mb-5 focus:outline-none focus:ring-2 focus:ring-crate-700/30 focus:border-crate-700 focus:bg-white transition-all duration-150"
        />

        {error && <p className="text-tomato-600 text-sm mb-4">{error}</p>}

        <button
          type="submit"
          disabled={submitting}
          className="w-full bg-gradient-to-b from-crate-700 to-crate-800 text-white rounded-full py-3 text-sm font-semibold hover:brightness-110 active:scale-[0.98] disabled:opacity-70 disabled:active:scale-100 transition-all duration-200"
        >
          {submitting ? "Resetting…" : "Reset password"}
        </button>

        <button
          type="button"
          onClick={() => navigate("/login")}
          className="w-full text-center text-xs text-crate-800/40 hover:text-crate-700 mt-4 transition-colors duration-150"
        >
          Back to sign in
        </button>
      </form>
    </div>
  );
}
